version: '3'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: tdb123
      MYSQL_DATABASE: db_doc_externo
    ports:
      - "3308:3306"
    networks:
      - my_network
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d

networks:
  my_network:
    driver: bridge
